name: unit test
on: 
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
    types: [opened, closed, reopened]
  workflow_dispatch:  
jobs:
    unit-test:
      runs-on: ${{ matrix.oss }}
      strategy:
        matrix:
          oss: [ubuntu-latest, macos-latest, windows-latest]
          nodes: [14, 16, 18]
      steps:
          - name: checking-out the code
            uses: actions/checkout@v4
          - name: setup Node
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.nodes }}
          - name: install dependencies
            run: npm ci  
          - name: unit-test
            run: npm run test
          - name: see the github-token
            run: echo '${{ github.triggering_actor }}'
          - name: check github run number
            run: echo '${{ github.run_number}}'

        
